name: deploy using docker compose

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - shell: bash
        env:
          DOCKER_COMPOSE: ${{ secrets.DOCKER_COMPOSE }}
        run: |
          echo "$DOCKER_COMPOSE" > compose.yml

      - name: build docker compose
        run: docker compose build

      - name: deploy docker compose
        run: docker compose up -d

      - name: cleanup unused docker images
        run: docker image prune -f
