name: deploy using Docker Compose

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: build docker compose
      run: docker compose build

    - name: deploy docker compose
      run: docker compose up -f /home/kiliups/docker/portfolio/compose.yaml -d

    - name: cleanup unused docker images
      run: docker image prune
